name: Build Container App
run-name: Build mcp-server by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: choice
        description: Image Tag
        options: 
          - "Dynamic (YYYY-mm-dd-COMMIT_REF)"
          - latest
        required: true

jobs:
  generate_dynamic_tag:
    runs-on: ubuntu-latest
    outputs:
      dynamic_tag: ${{ steps.generate.outputs.dynamic_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate Dynamic Tag
        id: generate
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d')
          COMMIT_REF=${{ github.sha }}
          echo "dynamic_tag=${TIMESTAMP}-${COMMIT_REF:0:7}" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: [generate_dynamic_tag]
    name: Build mcp-inspector 
    steps:
      - uses: actions/checkout@v4

      - name: Set Dynamic Image Tag
        run: |
          if [ "${{ github.event.inputs.image-tag }}" == "Dynamic (YYYY-mm-dd-COMMIT_REF)" ]; then
            echo "IMAGE_TAG=${{ needs.generate_dynamic_tag.outputs.dynamic_tag }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Check IMAGE_TAG
        run: |
          echo "IMAGE_TAG for build: ${{ env.IMAGE_TAG }}"

      - name: Add Image Tag to Job Summary
        run: |
          mkdir -p "$(dirname "$GITHUB_STEP_SUMMARY")"
          echo "### Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "IMAGE_TAG:${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "COMMIT_REF:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "SERVICE_NAME:mcp-inspector" >> $GITHUB_STEP_SUMMARY
          echo "ACTOR:${{ github.actor  }}" >> $GITHUB_STEP_SUMMARY

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: aiauksdocautomation.azurecr.io
          username: aiauksdocautomation
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image for mcp-inspector 
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: aiauksdocautomation.azurecr.io/mcp-inspector:${{ env.IMAGE_TAG }}