name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
            appSourcePath: ${{ github.workspace }}
            dockerfilePath: ./Dockerfile
            acrName: ca72f2f56ae9acr
            containerAppName: mcp-inspector
            resourceGroup: aia-uks-rg-container-environment
            targetPort: 6274
            ingress: external
            imageName: mcp-inspector-image  # Add or update this