name: Build and Deploy MCP Inspector
run-name: Build and deploy mcp-inspector by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      image-tag:
        type: choice
        description: Image Tag
        options: 
          - "Dynamic (YYYY-MM-DD-COMMIT_REF)"
          - latest
        required: true
        default: "Dynamic (YYYY-MM-DD-COMMIT_REF)"

jobs:
  generate_dynamic_tag:
    runs-on: ubuntu-latest
    outputs:
      dynamic_tag: ${{ steps.generate.outputs.dynamic_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate Dynamic Tag
        id: generate
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d')
          COMMIT_REF=${{ github.sha }}
          echo "dynamic_tag=${TIMESTAMP}-${COMMIT_REF:0:7}" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: [generate_dynamic_tag]
    name: Build and Push mcp-inspector Image
    steps:
      - uses: actions/checkout@v4

      - name: Set Dynamic Image Tag
        run: |
          if [ "${{ github.event.inputs.image-tag }}" == "Dynamic (YYYY-MM-DD-COMMIT_REF)" ]; then
            echo "IMAGE_TAG=${{ needs.generate_dynamic_tag.outputs.dynamic_tag }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Check IMAGE_TAG
        run: |
          echo "IMAGE_TAG for build: ${{ env.IMAGE_TAG }}"

      - name: Add Image Tag to Job Summary
        run: |
          echo "### Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "IMAGE_TAG:${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "COMMIT_REF:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "SERVICE_NAME:mcp-inspector" >> $GITHUB_STEP_SUMMARY
          echo "ACTOR:${{ github.actor }}" >> $GITHUB_STEP_SUMMARY

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
            registry: aiauksdocautomation.azurecr.io
            username: aiauksdocautomation
            password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image for mcp-inspector
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile  # Adjust if your Dockerfile path differs
          push: true
          tags: aiauksdocautomation.azurecr.io/mcp-inspector:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    name: Deploy to Azure Container App
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: aiauksdocautomation
          containerAppName: mcp-inspector
          resourceGroup: aia-uks-rg-container-environment
          imageToDeploy: aiauksdocautomation.azurecr.io/mcp-inspector:${{ needs.generate_dynamic_tag.outputs.dynamic_tag || 'latest' }}  # Matches the pushed tag
          targetPort: 6274
          ingress: external